version: "3.9"
services:
    web:
        build: ./springboot
        ports:
            - "8080:8080"
        links:
            - redis
    redis:
        build: ./redis
        image: "redis:alpine"
        hostname: containerizedredis
        ports:
            - "6379:6379"
